language: python
python:
  - "3.6"
services:
  - docker

before_install: pip install pipenv && pipenv lock --requirements > requirements.txt
# use travis-pls to force travis to behave.
# https://github.com/naftulikay/travis-pls
install: pip install travispls && pip install -r requirements.txt

script: travis-pls -m 7200 -i 300 ./build-docker.sh

deploy:
  skip_cleanup: true
  provider: script
  script: python upload.py
  # on:
    # branch: master
