language: python
python:
  - "3.6"
services:
  - docker
# use travis-pls to force travis to behave.
# https://github.com/naftulikay/travis-pls
install: pip install travispls

script: travis-pls -m 5400 ./build-docker.sh